---
title: "Assignment 4"
author: "Finn_Krüger"
date: "2023-11-09"
output: 
  html_document:
    toc: TRUE
    df_print: paged
    number_sections: FALSE
    highlight: tango
    theme: lumen
    toc_depth: 3
    toc_float: true
---


```{r setup, include=FALSE}
library(tm)
library(SnowballC)
library(dplyr)
library(tidyr)
library(quanteda)
library(NMF)
library(topicmodels)
library(tidytext)
library(LDAvis)
library(stm)
library(stopwords)
library(readr)
library(slam)
library(udpipe)
library(ggplot2)
library(seededlda)


```



## Creating the Dataset

```{r}

## Data 

df <- read_csv("df_o_tones.csv")

df
```

## Data Preprocessing 

```{r}

### list of all stop words

german_stopwords <- stopwords::stopwords("de", source = "stopwords-iso")

additional_stopwords <- c("mussen", "dass", "mehr", "dafur",
  "mussen", "deutschland", "setzen", "stark", "dafur", "brauchen", "land",  
  "fordern", "gesellschaft","braucht", "lehnen", "insbesondere", "starken", "deutlich", "gehort", "bleib", "ziel", "starken", "starke",
  "stark", "gilt", "deutschen", "deutsche", "deutsch","fur", "gemeinsame", "gemeinsam", "zudem", "leben", "bessere", "starker", "forder", "ford", "burger",'konnen', "uber", "buergerinnen", "moglich", "unseren", "gleichzeitig", "uber", "buergerinnen", "moglich", "unseren", "gleichzeitig", "demokraten", "linke", "prozent", "geben", "vgl", "freie",'nutzen', 'fuer', 'muessen','koennen', 'ueber', 'vieler', 'sagen', 'neu', 'koenn', 'gesetz', 'sag', 'sehen', 'naechst', 'lass', 'klar', 'letzter', 'heizungsgesetz','heut','dafuer','frag','frage', 'duerfen','stehen', 'wichtig', 'nehmen',
'woch', 'darueb', 'bekommen', 'abend', 'wuenschen', 'lassen', 'ð', 'Thema', 'fuehren', 'bring', 'darueber', 'regi', 'genau','wa', 'schaff', 'woche')

german_stopwords <- c(german_stopwords, additional_stopwords)

### preprocessing

df$Processed <- df$Processed %>%
  tolower() %>%
  removeWords(german_stopwords)%>%
  wordStem(language = "german") %>%
  gsub("[[:punct:]]", "", .) %>% 
  gsub("[ \t\r\n]+", " ", .) %>%
  gsub("[[:digit:]]", "", .) %>%
  trimws() 

# Remove empty rows -> dont go into the Dfmat 
df <- df[df$Processed != "", , drop = FALSE]

# create unique identifier for later   
df$id <-1:nrow(df)

```

```{r}


### creating document feautre matrix

dfmat <- df$Processed %>% 
  tokens() %>% 
  dfm() 

### Specifing alpha and iterations. 

#rowWords <- apply(dfmat, 1, sum)
#dfmat <- dfmat[rowWords > 0,]


# to mach later with the gammas '
rownames(dfmat) <- df$id 

```



## LDA

```{r}

#lda <- LDA(dfmat, k = 4, method = "Gibbs", control = list(iter = 100000,alpha = 0.1, delta = 0.5,  seed = 2))


lda <- LDA(dfmat, k = 10, method = "Gibbs", control = list(iter = 100000,alpha = 0.1, delta = 0.5,  seed = 2))




```



```{r}
# SEEEDED 

dict <- dictionary(list(
citizen_concerns_words = c("kosten", "sorgen", "miete", "buerger", "einkommen", "leute", "genuegend", "hausbesitzer", "belastung", "moeglichkeit", "verunsicherung", 'menschen', 'buergerinn', 'sozial'),
policy_words = c("gesetzentwurf", "waerer", "èol", "waermepumpe", "wasserstoff", "foerderung", "thema", "gebaeudeenergiegesetz", 'gasheizung', 'gas', "technologieoff", 'ausbau', 'waermepump', 'heiz', 'gasheiz'),
politics_words = c("politisch", "afd", "partei", "union", "opposition", "lindner", "habeck", "csu", "robert", "scholz", 'koalition',"heizung", "bundesregier", "parlament", "regierung", "kanzler", "bundestag", "ampel", 'spd', 'cdu', 'fdp', 'gruen', 'merz'),
climate_related_words = c("klimaneutral",'klima','klimawandel', 'klimaziele', 'klimaschutz', 'erneuerbar','klimaschutzgesetz', 'waermewend', 'energiewend')))
##klimabezug!!?
  
# Create a seeded LDA model
lda <- textmodel_seededlda(dfmat, residual = TRUE, beta = 0.01, dict, max_iter = 10000)


### topics() returns the most likely topics for documents based on the theta parameter.

check <- as.data.frame(topics(lda))# Print the data frame



nrow(lda$theta) ### Check with DF 

topic_words <- as.data.frame(terms(lda, n = 10))%>%
  rename(Climate_Context = climate_related_words,
         Policy = policy_words,
         Politics = politics_words,
         Citizens_Concerns = citizen_concerns_words)

write.csv(topic_words, "topic_words1.csv")


rownames(lda$theta) <- df$id 

### Create DF with 

Data_frame_theta <- as.data.frame(lda$theta)
Data_frame_theta$id <-1:nrow(Data_frame_theta)

doc_topics <- Data_frame_theta%>%
  left_join(df, by=c("id"="id"))

Document_Thetha <- doc_topics%>%
  select(affiliation, Processed, policy_words, politics_words, citizen_concerns_words, climate_related_words, other)%>%
  mutate(Row_sum = policy_words + politics_words + citizen_concerns_words + climate_related_words)

Document_Thetha_analysis <- Document_Thetha%>%
  group_by(affiliation)%>%
  summarise( Policy = mean(policy_words),
             Climate_context = mean(climate_related_words),
             Citizens_concerned = mean(citizen_concerns_words),
             Politics = mean(politics_words))%>%
  filter(!is.na(affiliation))%>%
  filter(!affiliation == 'Freie Wähler')



terms(lda, 50)
topics(lda)


```


```{r}

# Transpose the dataframe for better visualization
df_transposed <- t(Document_Thetha_analysis)

colnames(df_transposed) <- Document_Thetha_analysis$affiliation

df_transposed <- as.numeric(matrix(df_transposed[-1, ]))


df <- data.frame(
  affiliation = c("AFD", "ARD", "CDU/CSU", "Die Grünen", "Die Linke", "Expert", "FDP", "SPD"),
  Policy = c(0.1846046, 0.1800629, 0.1909450, 0.1929483, 0.2121789, 0.1995670, 0.2236829, 0.1865207),
  Climate_context = c(0.2003438, 0.2054113, 0.1897415, 0.2087309, 0.1747275, 0.1974081, 0.1826342, 0.2011668),
  Citizens_concerned = c(0.1997461, 0.1900944, 0.2129865, 0.2083282, 0.1898605, 0.1909823, 0.1789575, 0.2044264),
  Politics = c(0.2723743, 0.2448694, 0.2200378, 0.1975187, 0.1967499, 0.2154254, 0.2341383, 0.2005782)
)

# Set 'affiliation' column as row names
rownames(df) <- df$affiliation

# Select only numeric columns for the heatmap
mat <- as.matrix(df[, -1])

# Create heatmap
heatmap(mat, Rowv = NA, col = colorRampPalette(c("lightblue", "black"))(256),
        scale = "column", ylab = "Affiliation", margins = c(5, 10),mar = c(5, 4), symm=TRUE,
        cexRow = 0.9, cexCol = 0.9, cex.axis = 1)



Policy_per_Affiliation <- Document_Thetha_analysis%>%
  select(affiliation, Policy)

Climate_per_Affiliation <- Document_Thetha_analysis%>%
  select(affiliation, Climate_context)

Citizens_concerns_per_Affiliation <- Document_Thetha_analysis%>%
  select(affiliation, Citizens_concerned)

Politics_per_Afilliation <-  Document_Thetha_analysis%>%
  select(affiliation, Politics)



```



```{r}


matrix_data <- matrix(
  c(
    "Citizens Concerns", "Policy", "Politics", "Climate Context", "other", "social",
    "heating", "FDP", "climate protection", "quick", "citizen", "building energy law",
    "traffic light", "climate-neutral", "work", "people", "topic", "Habeck", "green", "answer",
    "worries", "wind", "green", "climate", "strong", "costs", "support", "CDU",
    "renewable", "speech", "money", "conflict", "coalition", "summer break", "try",
    "possibility", "heat pump", "opposition", "Berlin", "discussion", "income",
    "draft law", "parliament", "critique", "stay", "consult", "gas heating", "union",
    "cabinet", "construction", "citizen", "hydrogen", "party", "back", "create"
  ),
  ncol = 1,
  byrow = TRUE
)


```
